version: '3.8'

services:
  zipkin-0:
    image: openzipkin/zipkin
    container_name: cassandra-zipkin-tracing-tests_zipkin-00_1
    ports:
        - 9411:9411

  cassandra-00:
    build:
        context: .
        dockerfile: integration-cassandra.docker
    image: cassandra-zipkin-tracing:integration-cassandra
    container_name: cassandra-zipkin-tracing-tests_cassandra-00_1
    environment:
        CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
        CASSANDRA_CLUSTER_NAME: cluster1
        CASSANDRA_DC: dc1
        CASSANDRA_RACK: r1
    volumes:
         - ../../../.:/cassandra-zipkin-tracing
    healthcheck:
        test: ["CMD", "nc", "-z", "cassandra-00", "9042"]
        interval: 5s
        timeout: 10s
        retries: 60

  cassandra-01:
    build:
        context: .
        dockerfile: integration-cassandra.docker
    image: cassandra-zipkin-tracing:integration-cassandra
    container_name: cassandra-zipkin-tracing-tests_cassandra-01_1
    depends_on:
        - cassandra-00
    environment:
        CASSANDRA_SEEDS: cassandra-00
        CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
        CASSANDRA_CLUSTER_NAME: cluster1
        CASSANDRA_DC: dc1
        CASSANDRA_RACK: r2
        CASSANDRA_WAIT_ON: cassandra-00
        JVM_EXTRA_OPTS: '-Dcassandra.consistent.rangemovement=false -Dcassandra.ring_delay_ms=2000'
    volumes:
         - ../../../.:/cassandra-zipkin-tracing
    healthcheck:
        test: ["CMD", "nc", "-z", "cassandra-01", "9042"]
        interval: 5s
        timeout: 10s
        retries: 60

#  cassandra-02:
#    build:
#       context: .
#       dockerfile: integration-cassandra.docker
#    image: cassandra-zipkin-tracing:integration-cassandra
#    container_name: cassandra-zipkin-tracing-tests_cassandra-02_1
#    depends_on:
#       - cassandra-00
#    environment:
#       CASSANDRA_SEEDS: cassandra-00
#       CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
#       CASSANDRA_CLUSTER_NAME: cluster1
#       CASSANDRA_DC: dc2
#       CASSANDRA_RACK: r1
#       CASSANDRA_WAIT_ON: cassandra-00
#       JVM_EXTRA_OPTS: '-Dcassandra.consistent.rangemovement=false -Dcassandra.ring_delay_ms=2000'
#    volumes:
#         - ../../../.:/cassandra-zipkin-tracing
#    healthcheck:
#       test: ["CMD", "nc", "-z", "cassandra-02", "9042"]
#       interval: 5s
#       timeout: 10s
#       retries: 60
